apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhanu-deployment
spec:
  selector:
    matchLabels:
      app: Bhanu
  replicas: 2
  template:
    metadata:
      labels:
        app: Bhanu
    spec:
      containers:
        - name: bhanu-container
          image: tbhanuprasad/myrepo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
